import { Providers } from '@/providers'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
// import styles from './app.module.css'
import './globals.css'

const inter = Inter({ subsets: ['latin'], weight: ['300', '400', '500', '700'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang='en'>
            <body className={inter.className} suppressHydrationWarning={false}>
                <Providers>
                    {/* <main className={styles.contentApp}> */}
                    {children}
                    {/* </main> */}
                </Providers>
            </body>
        </html>
    )
}
